# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Medico' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  
  pod 'libPhoneNumber-iOS'

  target 'MedicoUITests' do
    pod 'libPhoneNumber-iOS'
  end

end
