name: android-development

on: push
#on:
#  pull_request:
#    branches: [ develop ]
#
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #     if: contains(github.event.head_commit.message, '[ANDROID]')

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      #        env:
      #          MSG: ${{ github.event.head_commit.message }}

      - name: Set CI gradle.properties
        run: cp gradle.properties.ci gradle.properties

      - name: Build Android apks
        env:
          CI_BUILD: ${{ secrets.CI_BUILD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: ./gradlew :android:assembleDev

      - name: Check dir
        run: |
          cd build
          ls

      - name: Check dir 2
        run: |
          cd build
          cd outputs
          ls

      - name: Check dir 3
        run: |
          cd build
          cd outputs
          cd apk
          ls

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/outputs/apk/dev/release/android-dev-release.apk
