name: android-development

on: push
#on:
#  pull_request:
#    branches: [ develop ]
#
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#     if: contains(github.event.head_commit.message, '[ANDROID]')

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build Android apks
        env:
          CI_BUILD: ${{ secrets.CI_BUILD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
#          GRADLE_OPTS: -Xmx4g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
        run: ./gradlew :android:assembleDev

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/android/dev/release/android-dev-release.apk
