name: android-development

on: push
#on:
#  pull_request:
#    branches: [ develop ]
#
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    if: contains(github.event.head_commit.message, '[ANDROID]')

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set CI gradle.properties
        run: cp gradle.properties.ci gradle.properties

      - name: Build Android apks
        env:
          CI_BUILD: ${{ secrets.CI_BUILD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: ./gradlew :android:assembleDev

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/build/outputs/apk/dev/release/android-dev-release.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID_DEV }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: main
          file: android/build/outputs/apk/dev/release/android-dev-release.apk